%% Build raw feature table from accelerometer data
function [features] = build_feature_table(...
    accel, sample_rate, order, cutoff)

    %% Generate data to use in features
    [low_b, low_a] = butter(order, cutoff / sample_rate);
    static_accel = filter(low_b, low_a, accel, [], 1);
    dynamic_accel = accel - static_accel;

    %% Make feature table
    disp("Generating features...");
    basic_stats = feature_basic_stats(accel);
    means = feature_means_extreme(accel);
    odba = feature_odba(dynamic_accel);
    pitch_and_roll = feature_pitch_and_roll(accel, static_accel);

    [tail_distinct, tail_freq] = feature_tailbeat(accel, sample_rate, 0.8, 1.6);

    features = table(...
        means(:,1), ...
        means(:,2), ...
        means(:,3), ...
        odba,...
        tail_distinct(:, 1), ...
        tail_distinct(:, 2), ...
        tail_distinct(:, 3), ...
        tail_freq(:, 1), ...
        tail_freq(:, 2), ...
        tail_freq(:, 3) ...
    );
    features.Properties.VariableNames = {...
        'means_x', 'means_y', 'means_z', ...
        'odba', ...
        'distinctiveness_x', 'distinctiveness_y', 'distinctiveness_z', ...
        'frequency_x', 'frequency_y', 'frequency_z' ...
    };

    features = [features, basic_stats];
    features = [features, pitch_and_roll];

end